name: Ruvchain

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --issues-exit-code=1

  codeql:
    name: Analyse
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.21", "1.22", "1.23", "1.24"]
    name: Build & Test (Linux, Go ${{ matrix.goversion }})
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goversion }}
      - name: Build Ruvchain
        run: go build -v ./...
      - name: Unit tests
        run: go test -v ./...

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.21", "1.22", "1.23", "1.24"]
    name: Build & Test (Windows, Go ${{ matrix.goversion }})
    needs: [lint]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goversion }}
      - name: Build Ruvchain
        run: go build -v ./...
      - name: Unit tests
        run: go test -v ./...

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.21", "1.22", "1.23", "1.24"]
    name: Build & Test (macOS, Go ${{ matrix.goversion }})
    needs: [lint]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goversion }}
      - name: Build Ruvchain
        run: go build -v ./...
      - name: Unit tests
        run: go test -v ./...

  build-freebsd:
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.21", "1.22", "1.23", "1.24"]
        goos:
          - freebsd
          - openbsd
    name: Build (Cross ${{ matrix.goos }}, Go ${{ matrix.goversion }})
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goversion }}
      - name: Build Ruvchain
        run: go build -v ./...
        env:
          GOOS: ${{ matrix.goos }}

  name: Build android
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
        
    - name: Check out Ruvchain
      uses: actions/checkout@v3
      with:
        repository: ruvcoindev/ruvchain
        path: ruvchain
        ref: master
        fetch-depth: 0
    
    - name: Setup Go environment
      uses: actions/setup-go@v3.3.1
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        ~/go/bin/gomobile init
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Install NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
      
    - name: Build Ruvchain
      run: |
        mkdir app/libs
        cd ruvchain
        PATH=$PATH:~/go/bin/ ./contrib/mobile/build -a
        cp {ruvchain.aar,ruvchain-sources.jar} ../app/libs
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Gradle build  
      if: github.event_name != 'release' && github.ref_name != 'main'
      run: |
        chmod +x gradlew
        ./gradlew buildRelease

    - name: Gradle signed build
      if: github.event_name == 'release' || github.ref_name == 'main'
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > app/gha.keystore.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --batch app/gha.keystore.asc > app/gha.jks
        chmod +x gradlew
        ./gradlew assembleRuvchain

    - name: Upload build artifact
      if: github.event_name == 'release' || github.ref_name == 'main'
      uses: actions/upload-artifact@v4
      with:
        name: ruvchain-android
        path: app/build/outputs/apk/ruvchain/app-ruvchain.apk
        
    - name: Upload release artifact
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: app/build/outputs/apk/ruvchain/app-ruvchain.apk
        asset_name: ruvchain-android.apk
        asset_content_type: application/vnd.android.package-archive
  tests-ok:
    name: All tests passed
    needs: [lint, codeql, build-linux, build-windows, build-macos, build-android]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Check all tests passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
